module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    CONFIRMATION: "CONFIRMATION",
    USERS_ADD_NEW: "USERS_ADD_NEW",
    CANDIDATES_ADD_NEW: "CANDIDATES_ADD_NEW",
    CANDIDATE_SCORE: "CANDIDATE_SCORE",
    COMPETITION_ADD_NEW: "COMPETITION_ADD_NEW",
    FINALIST_ADD: "FINALIST_ADD",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    CANDIDATES_DELETE: "CANDIDATES_DELETE",
    COMPETITION_DELETE: "COMPETITION_DELETE",
    USERS_DELETE: "USERS_DELETE",
    LOGOUT_USER: "LOGOUT_USER",
  },
});
